# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Computing brownian distance covariance using Rcpp
#' @description Computing brownian distance covariance of the input samples using Rcpp
#' @param x a group of samples
#' @param y a group of samples
#' @return the brownian distance covariance of the two groups of samples
#' @examples
#' \dontrun{
#' data(Eckerle4)
#' attach(Eckerle4)
#' dcov <- dcovC(Eckerle4$wavelength, Eckerle4$transmitance)
#' }
#' @export
dcovC <- function(x, y) {
    .Call(`_StatComp22009_dcovC`, x, y)
}

